source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'RMUniversalAlert' do

    pod 'UIAlertView+Blocks', '>= 0.8'
    pod 'UIActionSheet+Blocks', '>= 0.8'
    pod 'UIAlertController+Blocks', '>= 0.8'

end